package GUI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Main Game screen!
 */
public class GameScreen {
    private JTextPane playerInfo;
    private JLabel shipStatusLabel;
    private JLabel currentPortLabel;
    private JLabel targetPortLabel;
    private JTextPane shipStatusPane;
    private JTextPane currentPortPane;
    private JTextPane targetPortPane;
    private JButton toShipyardButton;
    private JButton toMarketplaceButton;
    private JButton toOceanMapButton;
    private JButton toTargetPortButton;

    private JPanel _panel;
    private static JFrame frame;

    private String _name;
    private String _coins;


    public GameScreen(String name, String coins) {
        _name = name;
        _coins = coins;
        updatePlayerInfoPane();
        toShipyardButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
        toMarketplaceButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                System.out.print("Displaying Marketplace Screen");
                GUI.GuiArbiter.MarketplaceScreen();
            }
        });
        toOceanMapButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });

        toTargetPortButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public void updatePlayerInfoPane(){
        playerInfo.setText("Name: " + _name + " You have: " + _coins + " coins");
    }

    public void updateCredits(String coins){
        _coins = coins;
        updatePlayerInfoPane();
    }

    public static void main(String[] args) {
        frame = new JFrame("Main Screen");
        frame.setContentPane(new GameScreen(args[0], args[1])._panel);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        _panel = new JPanel();
        _panel.setLayout(new FormLayout("fill:137px:noGrow,left:4dlu:noGrow,fill:173px:noGrow,left:4dlu:noGrow,fill:185px:noGrow", "center:51px:noGrow,top:6dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:260px:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        shipStatusLabel = new JLabel();
        shipStatusLabel.setText("Ship Status ");
        CellConstraints cc = new CellConstraints();
        _panel.add(shipStatusLabel, cc.xy(1, 3));
        currentPortLabel = new JLabel();
        currentPortLabel.setText("Current Port");
        _panel.add(currentPortLabel, cc.xy(3, 3));
        targetPortLabel = new JLabel();
        targetPortLabel.setText("Target Port");
        _panel.add(targetPortLabel, cc.xy(5, 3));
        shipStatusPane = new JTextPane();
        shipStatusPane.setEditable(false);
        _panel.add(shipStatusPane, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        currentPortPane = new JTextPane();
        currentPortPane.setEditable(false);
        _panel.add(currentPortPane, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.FILL));
        targetPortPane = new JTextPane();
        targetPortPane.setEditable(false);
        _panel.add(targetPortPane, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.FILL));
        playerInfo = new JTextPane();
        playerInfo.setEditable(false);
        playerInfo.setText("Name: Pilot: Fighter: Trader: Engineer:  You have: credits.");
        _panel.add(playerInfo, cc.xyw(1, 1, 5, CellConstraints.FILL, CellConstraints.TOP));
        toShipyardButton = new JButton();
        toShipyardButton.setText("Shipyard");
        _panel.add(toShipyardButton, cc.xy(1, 7));
        toMarketplaceButton = new JButton();
        toMarketplaceButton.setText("Marketplace");
        _panel.add(toMarketplaceButton, cc.xy(3, 7));
        toOceanMapButton = new JButton();
        toOceanMapButton.setText("Port Map");
        _panel.add(toOceanMapButton, cc.xy(5, 7));
        toTargetPortButton = new JButton();
        toTargetPortButton.setText("Warp to Target Port");
        _panel.add(toTargetPortButton, cc.xy(5, 9));
        shipStatusLabel.setLabelFor(shipStatusPane);
        currentPortLabel.setLabelFor(currentPortPane);
        targetPortLabel.setLabelFor(targetPortPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return _panel;
    }
}

