package GUI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created with IntelliJ IDEA.
 * User: ben
 * Date: 10/10/12
 * Time: 8:44 AM
 * To change this template use File | Settings | File Templates.
 */
public class GameScreen {
    private JTextPane playerInfo;
    private JLabel shipStatusLabel;
    private JLabel currentPlanetLabel;
    private JLabel targetPlanetLabel;
    private JTextPane shipStatusPane;
    private JTextPane currentPlanetPane;
    private JTextPane targetPlanetPane;
    private JButton toShipyardButton;
    private JButton toMarketplaceButton;
    private JButton toGalaxyMapButton;
    private JButton toTargetPlanetButton;

    private JPanel _panel;
    private static JFrame frame;


    public GameScreen() {
        toShipyardButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
        toMarketplaceButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
        toGalaxyMapButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });

        toTargetPlanetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void main(String[] args) {
        frame = new JFrame("Main Screen");
        frame.setContentPane(new GameScreen()._panel);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        _panel = new JPanel();
        _panel.setLayout(new FormLayout("fill:137px:noGrow,left:4dlu:noGrow,fill:173px:noGrow,left:4dlu:noGrow,fill:185px:noGrow", "center:51px:noGrow,top:6dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:260px:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        shipStatusLabel = new JLabel();
        shipStatusLabel.setText("Ship Status ");
        CellConstraints cc = new CellConstraints();
        _panel.add(shipStatusLabel, cc.xy(1, 3));
        currentPlanetLabel = new JLabel();
        currentPlanetLabel.setText("Current Planet");
        _panel.add(currentPlanetLabel, cc.xy(3, 3));
        targetPlanetLabel = new JLabel();
        targetPlanetLabel.setText("Target Planet");
        _panel.add(targetPlanetLabel, cc.xy(5, 3));
        shipStatusPane = new JTextPane();
        shipStatusPane.setEditable(false);
        _panel.add(shipStatusPane, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        currentPlanetPane = new JTextPane();
        currentPlanetPane.setEditable(false);
        _panel.add(currentPlanetPane, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.FILL));
        targetPlanetPane = new JTextPane();
        targetPlanetPane.setEditable(false);
        _panel.add(targetPlanetPane, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.FILL));
        playerInfo = new JTextPane();
        playerInfo.setEditable(false);
        playerInfo.setText("Name: Pilot: Fighter: Trader: Engineer:  You have: credits.");
        _panel.add(playerInfo, cc.xyw(1, 1, 5, CellConstraints.FILL, CellConstraints.TOP));
        toShipyardButton = new JButton();
        toShipyardButton.setText("Shipyard");
        _panel.add(toShipyardButton, cc.xy(1, 7));
        toMarketplaceButton = new JButton();
        toMarketplaceButton.setText("Marketplace");
        _panel.add(toMarketplaceButton, cc.xy(3, 7));
        toGalaxyMapButton = new JButton();
        toGalaxyMapButton.setText("Galaxy Map");
        _panel.add(toGalaxyMapButton, cc.xy(5, 7));
        toTargetPlanetButton = new JButton();
        toTargetPlanetButton.setText("Warp to Target Planet");
        _panel.add(toTargetPlanetButton, cc.xy(5, 9));
        shipStatusLabel.setLabelFor(shipStatusPane);
        currentPlanetLabel.setLabelFor(currentPlanetPane);
        targetPlanetLabel.setLabelFor(targetPlanetPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return _panel;
    }
}

