package GUI;

/**
 * Created with IntelliJ IDEA.
 * User: Venea
 * Date: 10/29/12
 * Time: 7:36 PM
 * To change this template use File | Settings | File Templates.
 */
import com.intellij.uiDesigner.core.GridLayoutManager;

import java.awt.*;
import javax.swing.*;

public class OceanMapPanel extends JPanel {

    public OceanMapPanel() {
        setBackground(Color.cyan);
    }
    private int _stupid=80;


    public void paintComponent(Graphics g) {

        super.paintComponent(g);

        g.setColor(Color.yellow);
        g.fillOval(0, 0, 80, get_stupid());
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    public int get_stupid() {
        return _stupid;
    }

    public void setStupid(int stupid) {
        _stupid = stupid;
    }
}
